start-location: '0,100,0 world'
join-location: '0,100,0 world'
craftable-items:
  - 'oak planks'
  - 'stick'
  - 'iron bars'
  - 'wooden pickaxe'
  - 'wooden axe'
  - 'wooden hoe'
  - 'wooden shovel'
  - 'wooden sword'
  - 'stone sword'
  - 'stone axe'
  - 'stone hoe'
  - 'stone shovel'
  - 'stone pickaxe'
  - 'crafting table'
  - 'iron sword'
  - 'iron axe'
  - 'iron hoe'
  - 'iron shovel'
  - 'iron pickaxe'
  - 'iron bars'
  - 'noteblock'
  - 'oak door'
  - 'oak fence'
  - 'oak stairs'
  - 'cobblestone stairs'
  - 'furnace'
  - 'ladder'
  - 'chest'
  - 'bread'
  - 'oak sign'
  - 'shears'