start-location: '0,100,0 world'
join-location: '0,100,0 world'
craftable-items:
  - 'oak planks'
  - 'spruce planks'
  - 'birch planks'
  - 'dark oak planks'
  - 'iron bars'
  - 'wooden pickaxe'
  - 'wooden axe'
  - 'wooden hoe'
  - 'wooden shovel'
  - 'wooden sword'
  - 'stone sword'
  - 'stone axe'
  - 'stone hoe'
  - 'stone shovel'
  - 'stone pickaxe'
  - 'crafting table'